Again
CODEKAPP/goit-team__Ice-cream pull request #72
Opened 2023-03-13 20:04 UTC by Sr-Drachen

Sorry, I did have it updated but I copied the code I had before and pasted it.

2023-03-13 23:52 UTC, CODEKAPP requested changes
update

2023-03-13 23:54 UTC, CODEKAPP commented on src/sass/base/_global.scss
> +  scroll-behavior: smooth;
este debe serr de forma automatica que solo calga undo se requiere si lo colocas asi siempre va a salir 
sin que se requiera

2023-03-14 00:05 UTC, Sr-Drachen commented on src/sass/base/_global.scss
> +  scroll-behavior: smooth;
Si se pone en auto, no se desliza, simplemente aparece en esa parte y se ve horrible

2023-03-14 00:15 UTC, closed without merging

2023-03-14 00:28 UTC, Sr-Drachen commented
Okey, yo no voy a pelear mas, tu haces lo que pictures